# .github/workflows/deploy-template.yml
name: Deploy Template

on:
  workflow_call:
    inputs:
      environment:
        description: 'Target environment (dev, uat, prod)'
        required: true
        type: string
      version:
        description: 'The version to deploy'
        required: true
        type: string
        
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Storing secret
        run: |
          echo "api_key = ${{ secrets.API_KEY }}" >> ~/apikey.txt"
      - name: Set up environment
        run: echo "Setting up environment for  ${{ vars.ACCESS_ENV }} and secret for ${{vars.ACCESS_ENV}} is $(cat ~/apikey.txt)"

      - name: Deploy to ${{ vars.ACCESS_ENV }}
        run: |
          echo "Deploying version ${{ inputs.version }} to ${{ vars.ACCESS_ENV }}"

      # Add more steps here to deploy, such as using SSH, Kubernetes, etc.
