name: Deploy Main

on:
  workflow_dispatch:
    inputs:
      vers:
        description: 'Version to deploy'
        required: true
        type: choice
        default: 'v1'
        options:
          - v1
          - v2
          - v3
          - v4
          - v5
          - v6
          - v7
      env:
        description: 'Env to deploy'
        required: true
        default: 'dev'
        type: choice
        options: 
          - dev
          - uat
          - prod

jobs:
  deploy-dev:
    uses: ./.github/workflows/deploy-template.yml
    if: ${{ inputs.env == 'dev' }}
    with:
      environment: ${{ inputs.env }}
      version: ${{ inputs.vers }}

  deploy-uat:
    if: ${{ inputs.env == 'uat' }}
    uses: ./.github/workflows/deploy-template.yml
    with:
      environment: ${{ inputs.env }}
      version: ${{ inputs.vers }}

  deploy-prod:
    if: ${{ inputs.env == 'prod' }}
    uses: ./.github/workflows/deploy-template.yml
    with:
      environment: ${{ inputs.env }}
      version: ${{ inputs.vers }}

