# .github/workflows/deploy-template.yml
name: Deploy Template

on:
  workflow_call:
    inputs:
      environment:
        description: 'Target environment (dev, uat, prod)'
        required: true
        type: string
      version:
        description: 'The version to deploy'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment
        run: echo "Setting up environment for ${{ env.ACCESS_ENV }} and token is ${{ secrets.ENV }}"

      - name: Deploy to ${{ env.ACCESS_ENV }}
        run: |
          echo "Deploying version ${{ inputs.version }} to ${{ env.ACCESS_ENV }}"

      # Add more steps here to deploy, such as using SSH, Kubernetes, etc.
